default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE_NAME'] %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>
  username: <%= ENV['DEV_DATABASE_USERNAME'] %>
  host: <%= ENV['DEV_DATABASE_HOST'] %>

test:
  <<: *default
  database: test_app4_test

production:
  <<: *default
  url: 'postgres://knxwiifglyywhv:e927d06c7580095681299359bb6d6d0d517ebaa29e2e768017513466c29a4c21@ec2-54-204-241-136.compute-1.amazonaws.com:5432/dauuih2umos9kg'

# For Docker based postgres database configuration
# development:
#   <<: *default
#   database: test_app4_development
#   password: 'mypassword'
#   username: myusername
#   host: 127.0.0.1
#   port: 54320

# For AWS RDS Postgres database configuration
# production:
#   <<: *default
#   database: test_app4_production
#   password: postgres1
#   username: postgres
#   host: interview-portal.c0z5yianmjla.us-east-1.rds.amazonaws.com
