default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE_NAME'] %>
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>
  username: <%= ENV['DEV_DATABASE_USERNAME'] %>
  host: <%= ENV['DEV_DATABASE_HOST'] %>

test:
  <<: *default
  database: test_app4_test

production:
  <<: *default
  url: <%= ENV['PROD_DATABASE_URL'] %>
  database: <%= ENV['PROD_DATABASE_NAME'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
  username: <%= ENV['PROD_DATABASE_USERNAME'] %>
  host: <%= ENV['PROD_DATABASE_HOST'] %>
# For Docker based postgres database configuration
# development:
#   <<: *default
#   database: test_app4_development
#   password: 'mypassword'
#   username: myusername
#   host: 127.0.0.1
#   port: 54320

# For AWS RDS Postgres database configuration
# production:
#   <<: *default
#   database: test_app4_production
#   password: postgres1
#   username: postgres
#   host: interview-portal.c0z5yianmjla.us-east-1.rds.amazonaws.com
