default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ddpqjt65a97271
  password: 'e16b60b805407d3da65eaafc712cd9214780e7cfb2beed921b11959a1aa37450'
  username: 'dzfrcqgalkxyit'
  host: 'ec2-107-23-76-12.compute-1.amazonaws.com'

test:
  <<: *default
  database: test_app4_test

production:
  <<: *default
  database: dauuih2umos9kg
  password: 'e927d06c7580095681299359bb6d6d0d517ebaa29e2e768017513466c29a4c21'
  username: 'knxwiifglyywhv'
  host: ec2-54-204-241-136.compute-1.amazonaws.com

# For Docker based postgres database configuration
# development:
#   <<: *default
#   database: test_app4_development
#   password: 'mypassword'
#   username: myusername
#   host: 127.0.0.1
#   port: 54320

# For AWS RDS Postgres database configuration
# production:
#   <<: *default
#   database: test_app4_production
#   password: postgres1
#   username: postgres
#   host: interview-portal.c0z5yianmjla.us-east-1.rds.amazonaws.com
